server:
  port: 8081

project:
  build:
    directory: target/


spring:
  application:
    name: AUTH-SERVICE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/jwt_auth_user
    username: root
    password: JC001
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      
      
security:
  jwt:
    secret-key: 8c3xjsu02yKxJKHYGsze0cA3V8fF3HWqbFVzHXZP5MtJxhtoi984pz0vUQLyL7H2
    expiration-time: 3600000
    
logging:
  level: 
    root: error


eureka:
  instance:
    prefer-ip-address: false
  client:
    enabled: false
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
