server:
  port: 8761

logging:
  level:
    root: error

spring:
  application:
    name: discovery-service
info:
  app:
    name: "Discovery and registery service"
    version: "1.0.0"
    description: "Ce service Ã  repertorier tous les microservices actifs"

eureka:
  server:
    expected-client-renewal-interval-seconds: 10

  client:
    register-with-eureka: false
    fetch-registry: false


